# Generated by Django 5.2.4 on 2025-07-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=100)),
                ('alert_time', models.DateTimeField()),
                ('report_type', models.CharField(default='people_count', max_length=50)),
                ('incount', models.PositiveIntegerField()),
                ('outcount', models.PositiveIntegerField()),
                ('occupancy', models.PositiveIntegerField()),
            ],
        ),
    ]
